#!/bin/sh
case $BUTTON in
	1) kitty -e pulsemixer ;;
	2) notify-send "🔊 Volume Block" "Left Click -> Audio Mixer\nRight Click -> Mute Audio\nScroll Wheel -> Change Volume" ;;
	3) pamixer -t ;;
	4) pamixer -i 5 --allow-boost ;;
	5) pamixer -d 5 --allow-boost ;;
	6) kitty -e nvim $0 ;;
esac

[ $(pamixer --get-mute) = true ] && echo "🔇 Muted" && exit

vol="$(pamixer --get-volume)"
if [[ $vol -ge 100 ]]; then
	pref="🔊"
elif [[ $vol -ge 50 ]]; then
	pref="🔉"
else
	pref="🔈"
fi

echo "$pref $vol%"
