#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall mpd                                                                                                                                                                                                                  
xrandr --output HDMI-A-0 --mode 1920x1080 -r 144 --pos 1920x0 --primary --output DisplayPort-2 --mode 1920x1080 -r 60 --pos 0x150                                                                                         
mpd &                                                                                                                                                                                                                        
dunst &                                                                                                                                                                                                                      
picom -b --experimental-backends &                                                                                                                                                                                           
feh --bg-fill --no-xinerama pix/wallhaven-oxo8gl_3840x1080.png &                                                                                                                                                             
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
eww open bar

bspc monitor DisplayPort-2		-d 1 2 3 4 5
bspc monitor HDMI-A-0			-d 1 2 3 4 5

bspc config border_width	 	2
bspc config window_gap			12

bspc config top_padding			40
bspc config bottom_padding		40
bspc config left_padding		80
bspc config right_padding		50

bspc config normal_border_color 	"#575268"
bspc config focused_border_color 	"#c9cbff"
bspc config active_border_color 	"#575268"

bspc config split_ratio			0.52
bspc config clock_to_focus		none
bspc config focus_follows_pointer	true

bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		none
bspc config pointer_action3		resize_corner
